version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.2.0.1
    container_name: nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_SERVERS=nacos-server:8848
    ports:
      - "8848:8848"  # Nacos 控制台和客户端访问的端口
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos-data:/home/nacos/data
    networks:
      - nacos-net
    restart: always

networks:
  nacos-net:
    driver: bridge

